DROP TABLE IF EXISTS  site_system.step;

CREATE TABLE site_system.step
(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    reader_num INT NOT NULL NULL DEFAULT 0,
    tag_num BIGINT UNSIGNED NOT NULL DEFAULT 0,
    user_num BIGINT UNSIGNED NULL DEFAULT 0,
    style INT NOT NULL DEFAULT 0,
    start DATETIME NOT NULL DEFAULT "2020-12-29 12:34:56",
    end DATETIME NOT NULL DEFAULT "2020-12-29 12:34:56",
    is_remove BOOLEAN NOT NULL DEFAULT FALSE
);
